def replace_char_in_word(guess, WORD, temp_word):
    for i in range(len(WORD)):        
        if guess == WORD[i]:
            temp_word = temp_word[:i] + guess + temp_word[i+1:]
    return temp_word
    

def draw_image(num):
            if num == 1:
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print("___________________")
            if num == 2:
                print ("       ___________")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print("___________________")
            if num == 3:
                print ("       ___________")
                print ("               \ |")
                print ("                \|")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print("___________________")
            if num == 4:
                print ("       ___________")
                print ("        |      \ |")
                print ("        |       \|")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print("___________________")
            if num == 5:
                print ("       ___________")
                print ("        |      \ |")
                print ("        |       \|")
                print ("        O        |")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print("___________________")
            if num == 6:
                print ("       ___________")
                print ("        |      \ |")
                print ("        |       \|")
                print ("        O        |")
                print ("        0        |")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print("___________________")
            if num == 7:
                print ("       ___________")
                print ("        |      \ |")
                print ("        |       \|")
                print ("        O        |")
                print ("        0/       |")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print("___________________")
            if num == 8:
                print ("       ___________")
                print ("        |      \ |")
                print ("        |       \|")
                print ("        O        |")
                print ("       \\0/       |")
                print ("                 |")
                print ("                 |")
                print ("                 |")
                print("___________________")
            if num == 9:
                print ("       ___________")
                print ("        |      \ |")
                print ("        |       \|")
                print ("        O        |")
                print ("       \\0/       |")
                print ("       /         |")
                print ("                 |")
                print ("                 |")
                print("___________________")

            if num == 10:
                print ("       ___________")
                print ("        |      \ |")
                print ("        |       \|")
                print ("        O        |")
                print ("       \\0/       |")
                print ("       / \       |")
                print ("                 |")
                print ("                 |")
                print ("__________________")